CREATE TABLE IF NOT EXISTS Department (
	id SERIAL PRIMARY KEY,
	Name VARCHAR(40) UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS Employee (
	id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT null,
	Department_id INTEGER REFERENCES Department(id));

ALTER TABLE Employee
ADD Chief_id INTEGER REFERENCES Employee(id);
