CREATE TABLE IF NOT EXISTS Executor (
id SERIAL PRIMARY KEY,
Name VARCHAR(70) NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre (
id SERIAL PRIMARY KEY,
Name VARCHAR(40) NOT NULL);

CREATE TABLE IF NOT EXISTS ArtistsGenre (
Executor_id INTEGER REFERENCES Executor(id),
Genre_id INTEGER REFERENCES Genre(id),
CONSTRAINT arge PRIMARY KEY (Executor_id, Genre_id));

CREATE TABLE IF NOT EXISTS Album (
id SERIAL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Yer INTEGER);

CREATE TABLE IF NOT EXISTS ExecutorAlbum (
Executor_id INTEGER REFERENCES Executor(id),
Album_id INTEGER REFERENCES Album(id),
CONSTRAINT exal PRIMARY KEY (Executor_id, Album_id));

CREATE TABLE IF NOT EXISTS Track (
id SERIAL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Duration TEXT,
Album_id INTEGER NOT NULL REFERENCES Album(id));

CREATE TABLE IF NOT EXISTS Collection (
id SERIAL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Yer INTEGER);

CREATE TABLE IF NOT EXISTS TrackCollection (
Track_id INTEGER REFERENCES Track(id),
Collection_id INTEGER REFERENCES Collection(id),
CONSTRAINT trco PRIMARY KEY (Track_id, Collection_id));
